name: Build

on: push

jobs:
  date-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test dates in CHANGELOG.md
      run:
        cat CHANGELOG.md | egrep '^#+ +[0-9-]+' | sed -r 's/([0-9]+)-([0-9]+)-([0-9]+)/\3-\2-\1/g' | sort --check -nr;

    - name: Test dates in source/includes/changelog/_changelog.md"
      run:
        cat source/includes/changelog/_changelog.md | egrep '^#+ +[0-9-]+' | sed -r 's/([0-9]+)-([0-9]+)-([0-9]+)/\3-\2-\1/g' | sort --check -nr;

  url-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test urls names in md files
        run:
          if cat source/includes/*/* | grep -i -n "api.moysklad.ru"; then
          cat source/includes/*/* | grep -i -n "api.moysklad.ru";
          exit 1;
          fi
