name: Build and Deploy k8s
on:
  push:
    branches: master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to DockerRegistry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/kladana-doc:${{ github.sha }}-release
          file: Dockerfile

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Set k8s config
        uses: azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
        id: login

      - name: Deploy k8s
        uses: azure/k8s-deploy@v4
        with:
          namespace: ${{ secrets.NAMESPACE_NAME }}
          manifests: |
            k8s/deploymentconfig.yaml
          images: |
            ${{ secrets.DOCKER_REGISTRY }}/kladana-doc:${{ github.sha }}-release
          imagepullsecrets: |
            imagepullsecret
